<table>
    <thead>
    <tr>
        <th>Nosaukums</th>
        <th>Apraksts</th>
        <th>Darbības</th>
    </tr>
    </thead>
    <tbody>
    <?php
    //Looping through the galleries
    foreach ($this->galerijas as $galerija) {

        echo "<tr>";
        echo "<td>" . $galerija['galleryTitle'] . "</td>";
        echo "<td>" . $galerija['galleryDescription'] . "</td>";
        echo "<td>";
        echo  "<a href=" . $this->url(array('action' => "rediget", "id" => $galerija['galleryId'])) . ">rediģēt</a>";
        echo  "&nbsp;/&nbsp;<a href=" . $this->url(array('action' => "dzest", "id" => $galerija['galleryId'])) . ">dzēst</a>";

        echo "</td>";
        echo "</tr>";

    }

    ?>
    </tbody>
</table>