<html>
<head>

    <style type="text/css">

        .center {
   width: 100px;
   height: 100px;
   position: absolute;
   left: 50%;
   top: 50%;
   margin-left: -50px;
   margin-top: -50px;
}
    </style>

</head>
<body>
<div class="center"><a href="<?php echo $this->url(array("action"=>'login','controller'=>'authentication'));?>"><img src="/images/nm_2863.jpg" alt="Pūpolītis"></a></div>



</body>
</html>