<?php
/**

 * User: Janis
 * Date: 12.22.3
 * Time: 18:09
 */

echo "<a href='".$this->url(array('action'=>"pievienot"))."'>Izveidot jaunu tipu</a>";
?>

<table>
    <thead><tr><th>Nosaukums</th><th>Apraksts</th><th>Darbības</th></tr></thead>
<?php
 foreach ($this->types as $type) {
    /** @var $type Model_Pasakumi_Type_Row */
    echo "<tr>";
    echo "<td>";
    echo $type->getTitle();
    echo "</td>";
    echo "<td>";
    echo $type->getDescription();
    echo "</td>";
        echo "<td>";
    echo "<a href='".$this->url(array('action'=>"rediget",'id'=>$type->getId()))."'>Rediģēt</a>";
     echo "&nbsp;/&nbsp;";
     echo "<a href='".$this->url(array('action'=>"punkti",'id'=>$type->getId()))."'>Punkti</a>";
     echo "&nbsp;/&nbsp;";
     echo "<a href='".$this->url(array('action'=>"dzest",'id'=>$type->getId()))."'>Dzēst</a>";
    echo "</td>";
    echo "</tr>";

}


    ?>

</table>
