<?php
/** View for admin points page for an event
 * @author Janis Peisenieks
 * @package Pasakumi
 * @subpackage Admin
 */
if($this->type!=null){
    ?>
<table>
    <thead><tr><th>Nosaukums</th><th>Apraksts</th></tr></thead>
    <?php
    $type=$this->type;
        /** @var $type Model_Pasakumi_Type_Row */
        echo "<tr>";
        echo "<td>";
        echo $type->getTitle();
        echo "</td>";
        echo "<td>";
        echo $type->getDescription();
        echo "</td>";
        echo "</tr>";




    ?>

</table>


<?php
echo $this->form;
}
