<?php foreach($this->pictures as $picture){
echo "<div class=\"content_box\">";
    if (Zend_Auth::getInstance()->hasIdentity() &&(Zend_Auth::getInstance()->getIdentity()->role === 'a')){
        echo "<p><a href='".$this->route."/bildes/dzest/id/".$picture['pictureId']."'>Dzēst bildi</a></p>";
    }
echo "<h2>".$picture['title']."</h2>";
echo "<p>".$picture['description']."</p>";
echo "<img src=\"".APP_DOMAIN."/images/uploaded/".$picture['pictureId'].".jpg\">";
echo "</div>";
}