<a href="<?php echo $this->url(array("action"=>'pievienot'));?>">Pievienot punktus</a>
<table>
    <thead>
    <tr><th>Vārds,Uzvārds</th><th>Krutums</th></tr>

    </thead>
<?php

foreach($this->krutums as $krutums){
    echo "<tr>";
    echo "<td><img src='".$krutums['icon']."' alt='".$krutums['name']."'/></td><td>".$krutums['name']."</td><td>".$krutums['krutumsCombined']."</td>";
     echo "</tr>";
}

?>
    </table>

