<a href="<?php echo $this->url(array("action"=>'pievienot'));?>">Pievienot punktus</a>
<table>
    <thead>
    <tr><th>Vārds,Uzvārds</th><th>Punkti</th></tr>

    </thead>
<?php

foreach($this->punkti as $punkti){
    echo "<tr>";
    echo "<td><img src='".$punkti['icon']."' alt='".$punkti['name']."'/></td><td>".$punkti['name']."</td><td>".$punkti['punktiCombined']."</td>";
     echo "</tr>";
}

?>
    </table>

