<?php foreach($this->turniri as $turnirs){?>
<div class="content_box">
    <center><img src="<?php echo $turnirs['logo'];?>" alt="<?php echo $turnirs['title'];?>" /></center>
    <strong><h2><a href="<?php echo $this->route."/turniri/skatit/id/".$turnirs['tournamentId']; ?>"><?php echo $turnirs['title'];?></a></h2></strong>
	<p>
	<?php echo $turnirs['description'];?>
	</p>
	<p>
	<?php
		if (time() > strtotime($turnirs['time'])) {
			echo "Turnīrs ir <strong><i>noticis</i></strong>: ";
		} else {
			echo "Turnīrs notiek: ";
		}
	?>	
	<strong>[<?php echo $turnirs['time'];?>]</strong>
	</p>
</div>	
<?php } ?>
