<div class="content_box">
    <center><img src="<?php echo $this->data['logo'];?>" alt="<?php echo $this->data['title'];?>"/></center>
    <strong><h2><a
            href="<?php echo $this->route . "/turniri/skatit/id/" . $this->data['tournamentId']; ?>"><?php echo $this->data['title'];?></a>
    </h2></strong>

    <p>
        <?php echo $this->data['description'];?>
    </p>

    <p>
        Organizē: <strong>[<a href="#"><?php echo $this->data['name'];?></a>]</strong>
        <?php
                if (time() > strtotime($this->data['time'])) {
        echo "Turnīrs ir <strong><i>noticis</i></strong>: ";
    } else {
        echo "Turnīrs notiek: ";
    }
        ?>
        <strong>[<?php echo $this->data['time'];?>]</strong>
    </p>

    <p>
        <?php
        if ($this->isOnline) {
            if ($this->isParticipating) {
                ?>
                [ <a href="<?php echo $this->route . "/komanda/dzest/id/" . $this->team['teamId']; ?>"> Atteikties
                    no dalības </a> ]
                <?php } else { ?>
                [ <a href="<?php echo $this->route . "/komanda/pievienot/id/" . $this->data['tournamentId']; ?>">
                    Pieteikties dalībai </a> ]
                <?php }
        } ?>
    </p>

        <?php

            if (!empty($this->pielikumi)) {
    echo  "<h3>" . Zend_Registry::get('Zend_Translate')->getAdapter()->translate('Pielikumi') . "</h3>";
}
    foreach ($this->pielikumi as $pielikums) {
        ?>
        <div class="content_box"> <?php if (Zend_Auth::getInstance()->hasIdentity() && ($this->data['tournamentOwner'] === Zend_Auth::getInstance()->getIdentity()->userId || Zend_Auth::getInstance()->getIdentity()->role === 'a')) {
            echo "<a href='" . $this->route . "/pielikums/dzest/id/" . $pielikums['attachmentId'] . "'>" . Zend_Registry::get('Zend_Translate')->getAdapter()->translate('Dzēst pielikumi') . "</a>";
        }?>
            <strong ><h2 ><a href ="<?php echo APP_DOMAIN.$pielikums['file']; ?>"><?php echo $pielikums['title'];?></a></h2></strong>
            <p>
                <?php echo $this->data['description'];?>
                <?php echo $pielikums['description']; ?>
            </p>
        </div>
        <?php } ?>
    <?php foreach ($this->jaunumi as $jaunumi) { ?>
    <div class="content_box">
        <h2><?php echo $jaunumi['title']; ?></h2>

        <p>
            <?php echo $jaunumi['content']; ?>
        </p>
    </div>
    <?php } ?>
</div>	
