<?php
/**
 * The default layout file for the admin section
 * @package Admin
 * @subpackage Admin
 */


echo $this->doctype ();
?>
<html>
<head>
	<?php
	echo $this->headMeta ();
	?>
	<?php
	echo $this->headTitle ();
	?>

	<?php
	echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/admin.css' )->appendStylesheet ( $this->baseUrl () . '/css/form.css' )->appendStylesheet ( $this->baseUrl () . '/js/jquery/css/global.css' )->appendStylesheet ( $this->baseUrl () . '/js/jquery/css/ui-lightness/jquery-ui-1.7.2.custom.css' )->appendStylesheet ( $this->baseUrl () . '/css/ui.daterangepicker.css' )->appendStylesheet($this->baseUrl() . '/css/shared.css');
	?>
<?php
	echo $this->headScript ()->prependFile ($this->baseUrl (). '/js/jquery-ui-1.8.16.custom.min.php', 'text/javascript', '' )->prependFile ($this->baseUrl (). '/js/jquery-1.6.2.min.js', 'text/javascript', '' );
        ?>
<style>
    .ui-datepicker{
       font-size: 11px;

    }
    .ui-timepicker-div .ui-widget-header { margin-bottom: 8px; font-size: 11px; }
.ui-timepicker-div dl { text-align: left; }
.ui-timepicker-div dl dt { height: 25px; margin-bottom: -25px; }
.ui-timepicker-div dl dd { margin: 0 10px 10px 65px; }
.ui-timepicker-div td { font-size: 20%; }
.ui-tpicker-grid-label { background: none; border: none; margin: 0; padding: 0; }

</style>
	<script type="text/javascript">
			$(function(){
				// Tabs
				$('#tabs').tabs();



			});
		</script>


</head>
<body>

<tr>
	<td colspan="6"><a href="/"><img id="PD_INTRA_NEWa_04"
		src="<?= APP_DOMAIN ?>/images/PD-INTRA-NEWa_04.gif" width="40" height="40" alt="" /></a></td>
	<td rowspan="9">
	<td><img id="PD_INTRA_NEWa_06" src="<?= APP_DOMAIN ?>/images/PD-INTRA-NEWa_06.gif"
		width="40" height="40" alt="" /></td>

	<td colspan="2"><img id="PD_INTRA_NEWa_08"
		src="../../images/PD-INTRA-NEWa_08.gif" width="40" height="40" alt="" /></td>
	<td><img id="PD_INTRA_NEWa_10" src="<?= APP_DOMAIN ?>/images/PD-INTRA-NEWa_10.gif"
		width="40" height="40" alt="" /></td>

</tr>
<?php
echo $this->title;
?>

		<div id="tabs" >
			<ul style="text-align:center;">
				<li><a href="#tabs-1">Mājaslapa</a></li>

			</ul>
			<div id="tabs-1">
<table width="100%" cellspacing="10px"><tr>
<td width="15%;" valign="top" class="ui-corner-all ui-widget-content" rowspan="2">


<h4 align="center">Menu</h4>
<?php
//$partial_menu = array('menu.phtml', 'default');
//$this->navigation()->menu()->setPartial($partial_menu);
echo $this->navigation ()->menu ()->renderMenu ($this->layout()->adminMenu);
?></div>

</td>

<td width="35%" align="center">
<div>
    <?php
    echo $this->partial('priorityMessages.phtml', array('priorityMessages' => $this->priorityMessenger()));
    ?>
    <?php
echo $this->layout ()->content;
?>
</td>

                        
                        
                        <td width="35%" valign="top">


</td>

   						
<tr valign="top">
<td  colspan="2">


</td>
</tr>  
</table>
		</div>			
</div>
<table width="100%" style="color:grey;">
<tr>
<td align="right">
<a href="/">Mājaslapa</a>  | &copy;<?php echo date("Y");?>
</td>
</tr>
</table>
</body>
</html>
