<?php
/** @var $translate Zend_Translate_Adapter */
$translate = Zend_Registry::get('Zend_Translate');

if (count($langs = $translate->getList()) > 1) {
    $req = Zend_Controller_Front::getInstance()->getRequest();



    $request = Zend_Registry::get('lang');
    unset($langs[$request]);
    echo '<div id="language list" class="rounded">';

    foreach ($langs as $lang) {
        $pr = $req->getParams();
        $params = '';
        if ($pr['module'] != 'default') {
            $params .= $pr['module'];

        }
        unset($pr['module']);
        if ($pr['controller'] != 'index') {
            $params .= '/' . $pr['controller'];
$params .= '/' . $pr['action'];
        }
        unset($pr['controller']);
       
        unset($pr['action']);
        unset($pr['language']);
        unset($pr['error_handler']);
        $pr['index']='change';
     //   var_dump($pr);
        foreach ($pr as $key => $value) {
            //var_dump($key);
            //var_dump($value);
            $params .= '/' . $key . '/' . $value;
        }
        echo '<div class="language"><a href="' . $this->baseUrl() . '/' . $lang . '' . $params . '"><img src="' . RESOURCE_PATH . '/' . $lang . '.png"/></a></div>';
    }
    echo '</div>';
}