<?php
if (sizeof($this->priorityMessages)) {
	echo '<div class="content_box">';
    echo '<div id="priority_messages" class="rounded">';
    echo '<ul>';
    foreach ($this->priorityMessages as $label=>$messages) {
        if (count($messages)) {
            echo '<li class="'.$label.'_message">';
            echo '<ul class="'.$label.'_message priority_message_container">';
            foreach ($messages as $message) {
                echo '<li>'.$message.'</li>';
            }
            echo '</ul></li>';
        }
    }
    echo '</ul>';
    echo '</div>';
	echo '</div>';
}